name: flutter_presentations
description: Presentations made with Flutter

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.0

  # Desktop embedder plugins.
  color_panel:
    path: ./plugins/color_panel
  file_chooser:
    path: ./plugins/file_chooser
  menubar:
    path: ./plugins/menubar

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true
  assets:
    - assets/google.png
    - assets/code.png
    - assets/demo.png
