name: flutter_presentations
description: Presentations made with Flutter

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true
  assets:
    - assets/

  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Monoserrat/Montserrat-Thin.ttf
          weight: 100
        - asset: fonts/Monoserrat/Montserrat-Light.ttf
          weight: 300
        - asset: fonts/Monoserrat/Montserrat-Regular.ttf
          weight: 400
        - asset: fonts/Monoserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: fonts/Monoserrat/Montserrat-Bold.ttf
          weight: 700
        - asset: fonts/Monoserrat/Montserrat-Black.ttf
          weight: 900
