name: flutter_presentations
description: Presentations made with Flutter

environment:
  sdk: ">=2.3.0-dev.0.3.flutter-c46deebfb6 <3.0.0"

dependencies:
  flutter_web: any
  flutter_web_ui: any
  presentation:
    path: ./dependencies/presentation

dev_dependencies:
  build_runner: ^1.4.0
  build_web_compilers: ^2.0.0
  pedantic: ^1.0.0

dependency_overrides:
  flutter_web:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web
  flutter_web_ui:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_ui
